Implementation of most GoF patterns
philips-ts/Task1 pull request #1
Opened 2022-09-19 18:30 UTC by philips-ts

2022-09-19 18:41 UTC, ALnOUA commented on src/main/java/com/tarasenko/gof_patterns/behavioral/CommandPattern.java
> +        }
We can use this code without "else"

2022-09-19 18:41 UTC, ALnOUA commented on src/main/java/com/tarasenko/gof_patterns/creational/abstract_factory/GUIFactory.java
> +        }
The same

2022-09-19 18:43 UTC, ALnOUA requested changes
Try to optimize your code and not to use checking that are useless

2022-09-20 10:24 UTC, philips-ts commented on src/main/java/com/tarasenko/gof_patterns/behavioral/CommandPattern.java
> +        }
Left as is

2022-09-20 10:24 UTC, philips-ts commented on src/main/java/com/tarasenko/gof_patterns/creational/abstract_factory/GUIFactory.java
> +        }
Done

2022-09-20 10:40 UTC, ALnOUA approved these changes

2022-09-20 10:47 UTC, merged