Subtask7
philips-ts/Task1 pull request #7
Opened 2022-11-07 15:52 UTC by philips-ts

2022-11-08 12:48 UTC, ALnOUA requested changes

2022-11-08 12:48 UTC, ALnOUA commented on src/main/java/com/tarasenko/shop/OnApplicationStartUp.java
> +    }
Also we can use @requiredargsconstractor for decreasing amount of code lines

2022-11-08 12:48 UTC, ALnOUA commented on src/main/java/com/tarasenko/shop/OnApplicationStartUp.java
> +}
Alternate way to init db it`s to  use liquibase and write migration

2022-11-08 12:48 UTC, ALnOUA commented on src/main/java/com/tarasenko/shop/OnApplicationStartUp.java
> +}
You can stay with this version but read about liquibase and migrations

2022-11-08 12:48 UTC, ALnOUA commented on src/main/java/com/tarasenko/shop/controller/MainController.java
> +    }
Can we make 3 separate contoller`s method and split this logic?

2022-11-08 12:48 UTC, ALnOUA commented on src/main/java/com/tarasenko/shop/controller/MainController.java
> +    @RequestMapping("/addToBucket")
I think it`s better to use pathvariable here
/addToBucket/{productId}

2022-11-08 12:48 UTC, ALnOUA commented on src/main/java/com/tarasenko/shop/dao/BucketDaoImpl.java
> +        }
Don`t forget about logs

2022-11-08 12:48 UTC, ALnOUA commented on src/main/java/com/tarasenko/shop/entity/Order.java
> +    private int id;
orderId

2022-11-08 12:48 UTC, ALnOUA commented on src/main/java/com/tarasenko/shop/entity/Product.java
> +    protected int id;
productId

2022-11-08 12:48 UTC, ALnOUA commented on src/main/java/com/tarasenko/shop/entity/User.java
> +
userId

2022-11-08 12:48 UTC, ALnOUA commented on src/main/java/com/tarasenko/shop/service/BucketServiceImpl.java
> +        }
Are we sure that getQuantity will not be return null?

2022-11-08 12:48 UTC, ALnOUA commented on src/main/java/com/tarasenko/shop/service/WarehouseServiceImpl.java
> +                .map(Optional::of)
productName.equalsIgnoreCase(product.getName()) will be better, in case of getName will be null

2022-11-08 12:48 UTC, ALnOUA commented on src/main/java/com/tarasenko/shop/service/FoodServiceImpl.java
> +        return foodDtos;
return foodMapper.toDto(allFood);

2022-11-17 23:02 UTC, philips-ts commented on src/main/java/com/tarasenko/shop/OnApplicationStartUp.java
> +    }
done

2022-11-17 23:02 UTC, philips-ts commented on src/main/java/com/tarasenko/shop/OnApplicationStartUp.java
> +}
done

2022-11-17 23:03 UTC, philips-ts commented on src/main/java/com/tarasenko/shop/entity/Product.java
> +    protected int id;
fixed

2022-11-17 23:03 UTC, philips-ts commented on src/main/java/com/tarasenko/shop/entity/User.java
> +
fixed

2022-11-17 23:05 UTC, philips-ts commented on src/main/java/com/tarasenko/shop/service/BucketServiceImpl.java
> +        }
It doesn't matter

2022-11-17 23:05 UTC, philips-ts commented on src/main/java/com/tarasenko/shop/service/WarehouseServiceImpl.java
> +                .map(Optional::of)
Fixed

2022-11-17 23:06 UTC, philips-ts commented on src/main/java/com/tarasenko/shop/service/FoodServiceImpl.java
> +        return foodDtos;
Fixed

2022-11-18 05:22 UTC, ALnOUA approved these changes

2022-11-18 05:22 UTC, ALnOUA commented on src/main/java/com/tarasenko/shop/entity/Order.java
Just a tip: @FieldDefaults(level = AccessLevel.PRIVATE)

2022-11-20 20:41 UTC, merged